# Custom Language File for Launcher Customizer

[ejs.app]
title = "Herpling PvP-Faction"

[ejs.landing]
mediaGitHubURL = "https://github.com/Herpling/HerplingLauncher"
mediaTwitterURL = "#"
mediaWebsiteURL = "https://sites.google.com/view/herpling-pvpfaction/home"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/sWKkZqUZCZ"

[ejs.settings]
sourceGithubLink = "https://github.com/Herpling/HerplingLauncher"
supportLink = "https://github.com/Herpling/HerplingLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR HERPLING"
welcomeDescription = "Bienvenue sur Herpling ! Plongez dans un univers où la survie repose sur votre habileté, votre stratégie et votre esprit d'équipe. Notre serveur offre une expérience de jeu palpitante où vous pouvez former des factions, forger des alliances et affronter vos adversaires dans des batailles épiques pour la suprématie."
welcomeDescCTA = "Vous êtes à quelques clics de Herpling."